services:
  # osrm:
  #   image: osrm/osrm-backend
  #   volumes:
  #     - ~/Documents/osm:/data
  #     - ./profiles:/profiles
  #   networks:
  #     - default
  #   ports:
  #     - 6000:5000
  #   restart: unless-stopped
  #   command: >
  #     bash -c "
  #     osrm-extract -p /profiles/foot.lua /data/singapore.osm.pbf && 
  #     osrm-partition /data/singapore.osrm && 
  #     osrm-customize /data/singapore.osrm && 
  #     osrm-routed \
  #     --algorithm mld \
  #     --max-matching-size 20000 \
  #     --max-viaroute-size 20000 \
  #     --max-trip-size 20000 \
  #     --max-table-size 20000 \
  #     /data/singapore.osrm
  #     "

  custom_osrm:
    image: osrm/osrm-backend
    volumes:
      - ./osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 9000:5000
    restart: unless-stopped
    command: >
      bash -c "
      osrm-extract -p /profiles/foot.lua /data/custom.osm && 
      osrm-partition /data/custom.osrm && 
      osrm-customize /data/custom.osrm && 
      osrm-routed \
      --algorithm mld \
      --max-matching-size 20000 \
      --max-viaroute-size 20000 \
      --max-trip-size 20000 \
      --max-table-size 20000 \
      /data/custom.osrm
      "  

networks:
  default:
    driver: bridge